Repository AIBootcamp14/mlops-project-mlops-5, pull requests merged in 2025-08, with the labels that each got.

#76 Update modeling and inference v.1.2.3
  .dockerignore
  .gitignore
  .paths/paths.env
  README.md
  requirements.txt
  scripts/inference/inference.py
  scripts/main.py
  scripts/postprocess/inference_to_db.py
  scripts/postprocess/inference_to_local.py
  scripts/postprocess/inference_to_s3.py
  scripts/webapp.py
  services/api/docker-compose.yml
  services/api/dockerfile
  services/model_inference/docker-compose.yml
Labels: modeling, mlflow, s3

#80 Update modeling/inference v1.2.5 and API 1.0.2
  README.md
  scripts/dataset/data_loader.py
  scripts/dataset/watch_log.py
  scripts/main.py
  scripts/model/movie_predictor.py
  scripts/webapp.py
  server1_tools_info.md
  server2_tools_info.md
  server3_tools_info.md
  services/api/docker-compose.yml
  services/api/dockerfile
  services/model_inference/docker-compose.yml
Labels: database, modeling, mlflow, fastapi

#86 Update modeling/Inference v1.4.3, API v1.4.3 and Add frontend 1.1.1
  .gitignore
  README.md
  data/raw/popular_movies_raw.json
  data/raw/watch_log.csv
  frontend/.gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
  models/movie_predictor/E500_T250805181336.pkl
  models/movie_predictor/E500_T250805181336.sha256
  scripts/data_prepare/save_to_db.py
  scripts/dataset/data_loader.py
  scripts/dataset/watch_log.py
  scripts/inference/inference.py
  scripts/main.py
  scripts/postprocess/inference_to_db.py
  scripts/webapp.py
  services/api/docker-compose.yml
  services/frontend/docker-compose.yml
  services/frontend/dockerfile
  services/model_inference/docker-compose.yml
Labels: database, modeling, serving, mlflow, fastapi, s3

#94 feat: 프로젝트 최종 서버1 완료
  .github/workflows/main.yml
  logs/docker-services/my-mlops-api/my-mlops-api_20250807_224833.log
  logs/docker-services/my-mlops-api/my-mlops-api_20250807_224944.log
  logs/docker-services/my-mlops-api/my-mlops-api_20250807_225057.log
  logs/docker-services/my-mlops-api/my-mlops-api_20250808_021319.log
  logs/docker-services/my-mlops-api/my-mlops-api_20250808_021939.log
  logs/docker-services/my-mlops-api/my-mlops-api_20250808_022503.log
  logs/docker-services/my-mlops-api/my-mlops-api_20250808_111129.log
  logs/docker-services/my-mlops-api/my-mlops-api_20250808_111950.log
  logs/docker-services/my-mlops-api/my-mlops-api_20250808_112125.log
  logs/docker-services/my-mlops-api/my-mlops-api_20250808_112247.log
  logs/docker-services/my-mlops-api/my-mlops-api_20250808_113359.log
  logs/docker-services/my-mlops-db/my-mlops-db_20250807_224833.log
  logs/docker-services/my-mlops-db/my-mlops-db_20250807_224945.log
  logs/docker-services/my-mlops-db/my-mlops-db_20250807_225057.log
  logs/docker-services/my-mlops-db/my-mlops-db_20250808_021320.log
  logs/docker-services/my-mlops-db/my-mlops-db_20250808_021940.log
  logs/docker-services/my-mlops-db/my-mlops-db_20250808_022504.log
  logs/docker-services/my-mlops-db/my-mlops-db_20250808_111130.log
  logs/docker-services/my-mlops-db/my-mlops-db_20250808_111951.log
  logs/docker-services/my-mlops-db/my-mlops-db_20250808_112127.log
  logs/docker-services/my-mlops-db/my-mlops-db_20250808_112248.log
  logs/docker-services/my-mlops-db/my-mlops-db_20250808_113400.log
  logs/docker-services/my-mlops-frontend/my-mlops-frontend_20250807_224834.log
  logs/docker-services/my-mlops-frontend/my-mlops-frontend_20250807_224946.log
  logs/docker-services/my-mlops-frontend/my-mlops-frontend_20250807_225058.log
  logs/docker-services/my-mlops-frontend/my-mlops-frontend_20250808_021322.log
  logs/docker-services/my-mlops-frontend/my-mlops-frontend_20250808_021941.log
  logs/docker-services/my-mlops-frontend/my-mlops-frontend_20250808_022505.log
  logs/docker-services/my-mlops-frontend/my-mlops-frontend_20250808_111132.log
  logs/docker-services/my-mlops-frontend/my-mlops-frontend_20250808_111952.log
  logs/docker-services/my-mlops-frontend/my-mlops-frontend_20250808_112128.log
  logs/docker-services/my-mlops-frontend/my-mlops-frontend_20250808_112250.log
  logs/docker-services/my-mlops-frontend/my-mlops-frontend_20250808_113403.log
  logs/docker-services/my-mlops-model/my-mlops-model_20250807_224834.log
  logs/docker-services/my-mlops-model/my-mlops-model_20250807_224946.log
  logs/docker-services/my-mlops-model/my-mlops-model_20250807_225059.log
  logs/docker-services/my-mlops-model/my-mlops-model_20250808_021323.log
  logs/docker-services/my-mlops-model/my-mlops-model_20250808_021942.log
  logs/docker-services/my-mlops-model/my-mlops-model_20250808_022507.log
  logs/docker-services/my-mlops-model/my-mlops-model_20250808_111133.log
  logs/docker-services/my-mlops-model/my-mlops-model_20250808_111953.log
  logs/docker-services/my-mlops-model/my-mlops-model_20250808_112129.log
  logs/docker-services/my-mlops-model/my-mlops-model_20250808_112251.log
  logs/docker-services/my-mlops-model/my-mlops-model_20250808_113404.log
  scripts/data_prepare/preprocessing.py
  scripts/dataset/watch_log.py
  scripts/postprocess/inference_to_db.py
  scripts/webapp.py
Labels: workhorse
